# Generated by Django 3.1.2 on 2020-11-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='usuario',
        ),
    ]
