# Generated by Django 3.1.2 on 2020-11-16 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('categoriadestacada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'CategoriaProducto',
                'verbose_name_plural': 'CategoriasProductos',
                'db_table': 'categories_products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MarcasProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('marcadestacada', models.BooleanField(default=False)),
                ('categoriamarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoriasproductos')),
            ],
            options={
                'verbose_name': 'MarcaProducto',
                'verbose_name_plural': 'MarcasProductos',
                'db_table': 'brand_products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('imagen', models.ImageField(blank=True, upload_to='productos/')),
                ('extracto', models.TextField(max_length=200, verbose_name='Extracto')),
                ('detalle', models.TextField(max_length=1000, verbose_name='Información del producto')),
                ('precio', models.FloatField()),
                ('precio_costo', models.FloatField()),
                ('disponible', models.BooleanField(default=True)),
                ('categoriasproductos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoriasproductos')),
                ('marcasproductos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.marcasproductos')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
    ]
